/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_JNI_I_SYM */

#ifndef _Included_org_example_JNI_I_SYM
#define _Included_org_example_JNI_I_SYM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_JNI_I_SYM
 * Method:    hexdump
 * Signature: (Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_org_example_JNI_1I_1SYM_hexdump
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    edge_crypto_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_edge_1crypto_1init
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    edge_crypto_final
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_edge_1crypto_1final
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    getCipherID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_getCipherID
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    init_EDGE_CIPHER_PARAMETERS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_JNI_1I_1SYM_init_1EDGE_1CIPHER_1PARAMETERS
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    init_key
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_example_JNI_1I_1SYM_init_1key
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_enc
 * Signature: (I[BIJ[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1enc
  (JNIEnv *, jobject, jint, jbyteArray, jint, jlong, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_dec
 * Signature: (I[BIJ[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1dec
  (JNIEnv *, jobject, jint, jbyteArray, jint, jlong, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_ctx_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_JNI_1I_1SYM_i_1ctx_1new
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_ctx_reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_JNI_1I_1SYM_i_1ctx_1reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_ctx_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_JNI_1I_1SYM_i_1ctx_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_enc_init
 * Signature: (JI[BIJ)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1enc_1init
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jlong);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_enc_update
 * Signature: (J[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1enc_1update
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_enc_final
 * Signature: (J[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1enc_1final
  (JNIEnv *, jobject, jlong, jbyteArray, jintArray);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_dec_init
 * Signature: (JI[BIJ)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1dec_1init
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jlong);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_dec_update
 * Signature: (J[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1dec_1update
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     org_example_JNI_I_SYM
 * Method:    i_dec_final
 * Signature: (J[B[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_example_JNI_1I_1SYM_i_1dec_1final
  (JNIEnv *, jobject, jlong, jbyteArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
